% perfil_teste_3.pl
resposta(1, n).
resposta(2, n).
resposta(3, n).
resposta(4, n).
resposta(5, n).
resposta(6, s).
resposta(7, s).
resposta(8, n).
resposta(9, s).
resposta(10, n).
resposta(11, s).
resposta(12, n).
resposta(13, n).
resposta(14, n).
resposta(15, n).
